spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml